### ISSUE TITLE
Error installing with pip - Docker

### ISSUE THREAD

**Issue by FreakyTea** [shinneider/django-admin-search#42]
Hi,

i currently updated to `django-admin-search 0.3.8` and tried building my Container after that. It gets me following error:

``` Collecting django-admin-search==0.3.8
#18 19.18   Downloading django-admin-search-0.3.8.tar.gz (49 kB)
#18 19.19   Preparing metadata (setup.py): started
#18 19.70   Preparing metadata (setup.py): finished with status 'error'
#18 19.70   ERROR: Command errored out with exit status 1:
#18 19.70    command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u2gyywqj/django-admin-search_6ace2ea415234adeb9a255046aacca76/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u2gyywqj/django-admin-search_6ace2ea415234adeb9a255046aacca76/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1m8huu2c
#18 19.70        cwd: /tmp/pip-install-u2gyywqj/django-admin-search_6ace2ea415234adeb9a255046aacca76/
#18 19.70   Complete output (7 lines):
#18 19.70   Traceback (most recent call last):
#18 19.70     File "<string>", line 1, in <module>
#18 19.70     File "/tmp/pip-install-u2gyywqj/django-admin-search_6ace2ea415234adeb9a255046aacca76/setup.py", line 7, in <module>
#18 19.70       from django_admin_search.meta import VERSION
#18 19.70     File "/tmp/pip-install-u2gyywqj/django-admin-search_6ace2ea415234adeb9a255046aacca76/django_admin_search/__init__.py", line 2, in <module>
#18 19.70       from django import __version__ as django_version
#18 19.70   ModuleNotFoundError: No module named 'django'
#18 19.70   ----------------------------------------
#18 19.70 WARNING: Discarding https://files.pythonhosted.org/packages/4c/6b/3603e90207855c7414386c20d0662f6a6a2ad18e6441a70f00c6614750b6/django-admin-search-0.3.8.tar.gz#sha256=f1b248b5e1706a75e64597b3eb21efd212576ac06eaec608bb0633e112b0d911 (from https://pypi.org/simple/django-admin-search/) (requires-python:>=3.3). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#18 19.70 ERROR: Could not find a version that satisfies the requirement django-admin-search==0.3.8 (from versions: 0.1.1, 0.2.2, 0.3, 0.3.1, 0.3.3, 0.3.5, 0.3.6, 0.3.7, 0.3.8)
#18 19.70 ERROR: No matching distribution found for django-admin-search==0.3.8
```

i moved django before django-admin-search in the requirements.txt but it didn't help.

This is my command for pip `pip install -r requirements.txt --no-cache-dir`

Do you have an idea what i could do here?

Best Regards

Fabian

**Comment by shinneider** [comment]
@FreakyTea  i generated a new version `0.3.9`....
you can try again and report status here ?

**Comment by FreakyTea** [comment]
@shinneider can confirm everything works now :) thanks for the fix!
